### ISSUE TITLE
How to install on windows

### ISSUE THREAD

**Issue by Tbd19** [evolvingweb/sitediff#17]
Provide instruction how to install sitediff on windows 7 / 10

**Comment by courtnafski** [comment]
Trying to run this on windows, but keeps getting multiple errors. I installed ruby 2.3.3 and sitediff and was getting an error about homepath and homedrives. That somehow resolved itself and now i am getting a libcurl error. No Libcurl in Ruby. Looks like the only thing in ruby is curb. Anyone have any thoughts or ideas on how to get this to work in windows 7? This seems like a great tool. I would really like to try it out. If this only requires Ruby, then I would think it should work on windows. If it does not, please update the description and explicitly state this.

**Comment by carehart** [comment]
@courtnafski, yours is a situation where Docker would seem the best solution. It really levels the playing field for Windows users wanting to use a tool like this. (Perhaps since writing last year, you may have done that.) 

If you were to spend just couple of hours getting an introduction to Docker, and then use the info above on using the sitediff container for it, that should get you going with sitediff and all its value. 

Better still, that knowledge and ability with docker would open a whole world of new possibilities with tools like it written for Linux, as well as with other capabilities in your work flow that easily make the effort worthwhile. 

I don't say all this to scold or condescend, but simply to encourage you (and others who may find this), as one on the other side of that wall you see. :) 

If you give it a go, let us know how you do.

**Comment by jigarius** [comment]
Unfortunately, it has been decided to not support SiteDiff on Windows. You can still run SiteDiff using Docker or a Virtual Machine.

I've updated the `INSTALLATION.md` file to say the same.
